[[redirects]]
  from = "/api/*"
  to = "http://15.164.151.83/:splat"
  status = 200


[[redirects]]
  from = "/api2/*"
  to = "http://ail.k-iacf.kr:84/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200